name: Release

on: push
  # release:
    # types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # with:
          # token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: test
        env:
          REPO: ${{ format('https://{0}:{1}@github.com/{2}.git', github.actor, 4, github.event.repository.name) }}
        run: |
          echo $REPO
      - name: install deps
        run: pip install -r requirements.txt
      - name: Autobump version
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ format('https://{0}:{1}@github.com/{2}.git', github.actor, github.token, github.event.repository.name) }}
          # REPO: https://${GITHUB_ACTOR}:${INPUT_GITHUB_TOKEN}@github.com/${REPOSITORY}.git
        run: |
          echo $REPO
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # from refs/tags/v1.2.3 get 1.2.3
          # VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
          # here last arg is mandatory but not used (cf https://github.com/c4urself/bump2version/issues/22)
          # bump2version --verbose --new-version $VERSION patch
          bump2version --verbose --new-version 0.3.8 patch
          # push
          git push $REPO HEAD:main
          # git push https://${{ github.repository_owner }}:${{ github.token }}@github.com/${{ github.event.repository.name }} HEAD:master