name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (vA.B.C)'
        required: true
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install bumpversion
        run: pip install -r requirements.txt
      - name: Bump version from release
        shell: bash
        env:
          VERSION: ${{ github.event.inputs.version }}
        run: |
          VERSION_NUMBER=$(echo ${VERSION:1})
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # here last arg is mandatory but not used (cf https://github.com/c4urself/bump2version/issues/22)
          bump2version --verbose --new-version $VERSION_NUMBER patch
      # this won't trigger an other workflow because github token is used and not personal_access_token
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}  # name of branch choosed in workflow dispatch
      # here we could continue and publish to pypi
      # and then we can create the release
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false