name: Release

on: push
  # release:
    # types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: install deps
        run: pip install -r requirements.txt
      - name: Autobump version
        shell: bash
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          # from refs/tags/v1.2.3 get 1.2.3
          # VERSION=$(echo $GITHUB_REF | sed 's#.*/v##')
          # here last arg is mandatory but not used (cf https://github.com/c4urself/bump2version/issues/22)
          # bump2version --verbose --new-version $VERSION patch
          bump2version --verbose --new-version 0.3.8 patch
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}